# sync_droptank.ps1 - copy the whole mods\DropTank folder (mod.json + config + code dll) to every
# install that already carries the other mods. dist\ and dist_upload\ are NOT touched: those are
# regenerated by tools\pack_release.py from Aviassembly_DEV\mods (GAME_MODS).
# ASCII-only; paths derived from $PSScriptRoot. Output -> _deploy_report_droptank.txt
$ErrorActionPreference = "Continue"

$root = Split-Path $PSScriptRoot -Parent          # Machine_Dev
$parent = Split-Path $root -Parent                # D:\...\
$srcDir = Join-Path $parent "Aviassembly_DEV\mods\DropTank"

$sb = New-Object System.Text.StringBuilder
function Say($s) { [void]$sb.AppendLine([string]$s) }
function Flush { [System.IO.File]::WriteAllText((Join-Path $root "_deploy_report_droptank.txt"), $sb.ToString(), (New-Object System.Text.UTF8Encoding($false))) }

if (-not (Test-Path $srcDir)) { Say ("MISSING SOURCE " + $srcDir); Flush; exit 1 }

$alive = Get-Process -Name "Aviassembly" -ErrorAction SilentlyContinue
Say ("game running = " + [bool]$alive + "  (steam install is skipped while it runs)")
Say ("src = " + $srcDir)

$files = @("mod.json", "droptank_config.json")
$dll = Join-Path (Join-Path $srcDir "code") "DropTank.dll"
if (-not (Test-Path $dll)) { Say ("MISSING DLL " + $dll); Flush; exit 1 }
$dllMd5 = (Get-FileHash $dll -Algorithm MD5).Hash.ToLower()
Say ("dll = " + (Get-Item $dll).Length + " bytes  md5=" + $dllMd5)

$targets = @(
    (Join-Path $parent "MachineLoader_work\mods\DropTank"),
    (Join-Path $parent "MachineLoader_github\MachineLoader-main\mods\DropTank"),
    "D:\steam\steamapps\common\Aviassembly\mods\DropTank"
)

foreach ($t in $targets) {
    $skip = $alive -and ($t -like "D:\steam\*")
    if ($skip) { Say ("SKIP (game running) " + $t); continue }
    try {
        $code = Join-Path $t "code"
        if (-not (Test-Path $code)) { New-Item -ItemType Directory -Force -Path $code | Out-Null }
        foreach ($f in $files) { Copy-Item (Join-Path $srcDir $f) (Join-Path $t $f) -Force }
        Copy-Item $dll (Join-Path $code "DropTank.dll") -Force
        $n = Get-Item (Join-Path $code "DropTank.dll")
        $m = (Get-FileHash (Join-Path $code "DropTank.dll") -Algorithm MD5).Hash.ToLower()
        Say (($(if ($m -eq $dllMd5) { "OK   " } else { "MISMATCH " })) + $n.Length + "  " + $m.Substring(0, 12) + "  " + $t)
    } catch {
        Say ("FAIL " + $t + " :: " + $_.Exception.Message)
    }
}
Flush
